# uds-package.yaml

---
apiVersion: uds.dev/v1alpha1
kind: Package
metadata:
  namespace: kaiju
  name: kaiju
spec:
  network:
    expose:
      - service: backend
        selector:
          app.kubernetes.io/component: backend
        host: kaiju
        port: 8000
    allow:
      - description: Backend to database
        direction: Egress
        selector:
          app.kubernetes.io/component: backend
        remoteNamespace: kaiju
        remoteSelector:
          app.kubernetes.io/component: database
        port: 5432
      - description: Database from backend
        direction: Ingress
        selector:
          app.kubernetes.io/component: database
        remoteNamespace: kaiju
        remoteSelector:
          app.kubernetes.io/component: backend
        port: 5432
  sso:
    - name: Kaiju
      clientId: kaiju
      redirectUris:
        - https://kaiju.uds.dev/login
      enableAuthserviceSelector:
        app.kubernetes.io/component: backend
    - name: Kaiju UAT
      clientId: kaiju-uat
      standardFlowEnabled: false
      serviceAccountsEnabled: true
      protocolMappers:
        - name: audience
          protocol: openid-connect
          protocolMapper: oidc-audience-mapper
          config:
            included.client.audience: "kaiju"
            access.token.claim: "true"
            introspection.token.claim: "true"
            id.token.claim: "false"
            lightweight.claim: "false"
            userinfo.token.claim: "false"
