# Generated by Django 6.1 on 2026-09-04 21:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("objectives", "0001_initial"),
        ("references", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Exercise",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("scheduled_start_time", models.DateTimeField()),
                ("scheduled_end_time", models.DateTimeField()),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("discussion", "Discussion"),
                            ("discussion_and_hands_on", "Discussion And Hands On"),
                        ],
                        default="discussion",
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("scenario", models.TextField()),
                ("opfor_coordinated_at", models.DateTimeField(blank=True, null=True)),
                ("read_aheads_sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("prepared", "Prepared"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                        ],
                        default="planned",
                        max_length=20,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="exercises_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "objectives",
                    models.ManyToManyField(
                        blank=True, related_name="exercises", to="objectives.objective"
                    ),
                ),
                (
                    "references",
                    models.ManyToManyField(
                        blank=True, related_name="exercises", to="references.reference"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("number", models.PositiveIntegerField()),
                ("description", models.CharField(max_length=255)),
                (
                    "objectives",
                    models.ManyToManyField(
                        blank=True, related_name="events", to="objectives.objective"
                    ),
                ),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="exercises.exercise",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Finding",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("sustainment", "Sustainment"),
                            ("improvement", "Improvement"),
                        ],
                        max_length=20,
                    ),
                ),
                ("topic", models.CharField(max_length=50)),
                ("observation", models.TextField()),
                ("recommendation", models.TextField()),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="findings_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="findings",
                        to="exercises.exercise",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Participant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("facilitator", "Facilitator"),
                            ("information_system_owner", "Iso"),
                            ("information_system_security_manager", "Issm"),
                            ("information_system_security_officer", "Isso"),
                            ("system_administrator", "System Administrator"),
                            ("user", "User"),
                            ("cybersecurity_service_provider", "Cssp"),
                            ("opposing_force", "Opfor"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="exercises.exercise",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Inject",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("scheduled_start_time", models.DateTimeField()),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("number", models.CharField(max_length=10)),
                (
                    "delivery_method",
                    models.CharField(
                        choices=[
                            ("index_card", "Index Card"),
                            ("phone_call", "Phone Call"),
                            ("email", "Email"),
                            ("chat_message", "Chat Message"),
                        ],
                        max_length=20,
                    ),
                ),
                ("sender", models.CharField(max_length=100)),
                ("message", models.TextField()),
                ("expected_response", models.TextField(blank=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="injects",
                        to="exercises.event",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="injects_received",
                        to="exercises.participant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Response",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("text", models.TextField()),
                (
                    "inject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="exercises.inject",
                    ),
                ),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="exercises.participant",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="event",
            constraint=models.UniqueConstraint(
                fields=("exercise", "number"), name="unique_event_number_per_exercise"
            ),
        ),
        migrations.AddConstraint(
            model_name="participant",
            constraint=models.UniqueConstraint(
                fields=("exercise", "email"), name="unique_participant_per_exercise"
            ),
        ),
        migrations.AddConstraint(
            model_name="inject",
            constraint=models.UniqueConstraint(
                fields=("event", "number"), name="unique_inject_number_per_event"
            ),
        ),
    ]
