# Generated by Django 6.1 on 2026-08-29 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exercises", "0001_initial"),
        ("objectives", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="objective",
            name="unique_objective_number_per_exercise",
        ),
        migrations.RemoveField(
            model_name="event",
            name="related_objectives",
        ),
        migrations.RemoveField(
            model_name="facilitatorquestion",
            name="related_objectives",
        ),
        migrations.AddField(
            model_name="exercise",
            name="objectives",
            field=models.ManyToManyField(
                blank=True, related_name="exercises", to="objectives.objective"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="related_objectives",
            field=models.ManyToManyField(
                blank=True, related_name="events", to="objectives.objective"
            ),
        ),
        migrations.AddField(
            model_name="facilitatorquestion",
            name="related_objectives",
            field=models.ManyToManyField(
                blank=True,
                related_name="facilitator_questions",
                to="objectives.objective",
            ),
        ),
        migrations.DeleteModel(
            name="Objective",
        ),
    ]
