# Generated by Django 6.0.7 on 2026-08-27 03:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exercises", "0001_initial"),
        ("references", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("number", models.PositiveIntegerField()),
                ("description", models.TextField()),
                ("expected_actions", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Exercise",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("discussion", "Discussion"),
                            ("discussion_and_hands_on", "Discussion And Hands On"),
                        ],
                        default="discussion",
                        max_length=30,
                    ),
                ),
                ("start_date_time", models.DateTimeField()),
                ("end_date_time", models.DateTimeField()),
                ("title", models.CharField(max_length=100)),
                ("scenario", models.TextField()),
                (
                    "red_team_coordinated_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("read_aheads_sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("prepared", "Prepared"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                        ],
                        default="planned",
                        max_length=20,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="exercises_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "facilitator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="exercises_facilitated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "references",
                    models.ManyToManyField(
                        blank=True, related_name="exercises", to="references.reference"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FacilitatorQuestion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("question", models.TextField()),
                ("number", models.PositiveIntegerField()),
                ("expected_answer", models.TextField(blank=True)),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="facilitator_questions",
                        to="exercises.exercise",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Inject",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("number", models.CharField(max_length=10)),
                ("scheduled_start_time", models.DateTimeField()),
                (
                    "delivery_method",
                    models.CharField(
                        choices=[
                            ("index_card", "Index Card"),
                            ("phone_call", "Phone Call"),
                            ("email", "Email"),
                            ("chat_message", "Chat Message"),
                        ],
                        max_length=20,
                    ),
                ),
                ("sender", models.CharField(max_length=100)),
                ("recipient", models.CharField(max_length=100)),
                ("message", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Objective",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("number", models.PositiveIntegerField()),
                ("description", models.TextField()),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="objectives",
                        to="exercises.exercise",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Reference",
        ),
        migrations.AddField(
            model_name="event",
            name="exercise",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="exercises.exercise",
            ),
        ),
        migrations.AddField(
            model_name="inject",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="injects",
                to="exercises.event",
            ),
        ),
        migrations.AddField(
            model_name="facilitatorquestion",
            name="related_objectives",
            field=models.ManyToManyField(
                blank=True,
                related_name="facilitator_questions",
                to="exercises.objective",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="related_objectives",
            field=models.ManyToManyField(
                blank=True, related_name="events", to="exercises.objective"
            ),
        ),
        migrations.AddConstraint(
            model_name="inject",
            constraint=models.UniqueConstraint(
                fields=("event", "number"), name="unique_inject_number_per_event"
            ),
        ),
        migrations.AddConstraint(
            model_name="objective",
            constraint=models.UniqueConstraint(
                fields=("exercise", "number"),
                name="unique_objective_number_per_exercise",
            ),
        ),
        migrations.AddConstraint(
            model_name="facilitatorquestion",
            constraint=models.UniqueConstraint(
                fields=("exercise", "number"),
                name="unique_facilitator_question_number_per_exercise",
            ),
        ),
        migrations.AddConstraint(
            model_name="event",
            constraint=models.UniqueConstraint(
                fields=("exercise", "number"), name="unique_event_number_per_exercise"
            ),
        ),
    ]
