name: Integrate

on:
  push:
    branches: [ "**" ]
    paths:
      - "backend/**"
      - "frontend/**"
      - "docs/**"

jobs:
  secrets:
    name: Secrets Check
    runs-on: ubuntu-latest
    steps:
      - name: Clone the repository
        uses: actions/checkout@v4
      - name: Run Trufflehog
        id: trufflehog
        uses: trufflesecurity/trufflehog@main
        continue-on-error: false

  dockerfile:
    name: Dockerfile Lint Check
    needs: secrets
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        container:
          - backend
          - frontend
          - docs
    steps:
      - uses: actions/checkout@v4
      - uses: hadolint/hadolint-action@v3.1.0
        with:
          failure-threshold: error
          dockerfile: ${{ matrix.container }}/Dockerfile

  qa:
    name: Quality Assurance Check
    needs: secrets
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        container:
          - backend
          - frontend
          - docs
    steps:
      - name: Clone the repository
        uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install Python dependencies
        run: python -m pip install black
      - name: Check code formatting
        run: black --diff --color --check ${{ matrix.container }}

  sca:
    name: Software Composition Analysis
    needs: secrets
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: write
    strategy:
      fail-fast: false
      matrix:
        container:
          - backend
          - frontend
          - docs
    steps:
      - uses: actions/checkout@v4
      - name: Generate an SBOM
        uses: anchore/sbom-action@v0
        with:
          path: ${{ matrix.container }}
          output-file: sbom-${{ matrix.container }}.json
          artifact-name: sbom-${{ matrix.container }}
      - name: Check for CVEs
        uses: anchore/scan-action@v3
        with:
          sbom: sbom-${{ matrix.container }}.json
          severity-cutoff: high

  sast:
    name: Static App Security Test
    needs: secrets
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        container:
          - backend
          - frontend
          - docs
    container:
      image: semgrep/semgrep
    steps:
      - name: Clone the repository
        uses: actions/checkout@v4
      - name: Perform a SAST scan
        run: semgrep scan --config auto ${{ matrix.container }}
